name: Build All Docker Images

on:
  push:
    branches: [ "main" ]
    paths:
      - '**/Dockerfile'  # Trigger when any Dockerfile changes
      - '**/docker-compose.yml'  # Optional: include compose file changes
  workflow_dispatch:

env:
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
  DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Auto-discover all directories containing Dockerfiles
        service: ${{ fromJson(needs.discover.outputs.services) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ env.DOCKER_HUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.DOCKER_HUB_USERNAME }}/${{ matrix.service }}
          tags: |
            type=ref,event=branch
            type=sha,format=short

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./${{ matrix.service }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  # This job finds all directories with Dockerfiles
  discover:
    runs-on: ubuntu-latest
    outputs:
      services: ${{ steps.find-services.outputs.services }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Find all Dockerfile locations
        id: find-services
        run: |
          SERVICES=$(find . -name 'Dockerfile' -exec dirname {} \; | sed 's|^./||' | jq -R -s -c 'split("\n")[:-1]')
          echo "services=${SERVICES}" >> $GITHUB_OUTPUT
